### ISSUE TITLE
Could the readme file be more clear?

### ISSUE THREAD

**Issue by Ophelia-Wang** [alceballosa/deform-aneurysm-detection#1]
For example, what is the function of each folder, and which directories need to be changed if you need to test locally. You can also put a test case.
I'm sorry this is a bother for you, but it's really important to us.

**Comment by alceballosa** [comment]
Hi @Ophelia-Wang !

No worries, the original version was not intuitive at all to run. I've modified the README to abstract away most of the steps so that you can run everything in just a few steps while defining a single input path. I tested it on a clean environment and was able to run inference on a couple test cases with minimal effort. Let me know if you can run it this way or if you run across any bugs. Do note that you still need to place the weights inside a pre-defined location within the repository. I may try to compress the weights file to see if it can fit under the 100 MB limit in the future though.

Best,

Alberto

**Comment by Ophelia-Wang** [comment]
@alceballosa Thank you very much！
